In [ ]:
import pandas as pd
import numpy as np

In [ ]:
train = pd.read_csv('data/train.csv')
test = pd.read_csv('data/test.csv')

In [ ]:
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
train['title'] = train['Name'].str.split(',', expand= True)[1].str.split('.', expand = True)[0].str.strip()
train['apha_ticket'] = np.where(train['Ticket'].str.contains('[A-Za-z]') , 1, 0)
train['cabin_type'] = train['Cabin'].str[:1]
train['Pclass'] = train['Pclass'].astype(str)

In [ ]:
test['title'] = test['Name'].str.split(',', expand= True)[1].str.split('.', expand = True)[0].str.strip()
test['apha_ticket'] = np.where(test['Ticket'].str.contains('[A-Za-z]') , 1, 0)
test['cabin_type'] = test['Cabin'].str[:1]
test['Pclass'] = test['Pclass'].astype(str)

In [ ]:
train = train.drop(['Name','Ticket', 'Cabin', 'PassengerId'], axis = 1)
test = test.drop(['Name','Ticket', 'Cabin', 'PassengerId'], axis = 1)

In [ ]:
test['Survived'] = None

In [ ]:
from feature_engine.imputation import MeanMedianImputer

median_imputer = MeanMedianImputer(
                   imputation_method='median',
                   variables=['Age', 'Fare']
                   )

# fit the imputer
median_imputer.fit(train)

MeanMedianImputer(variables=['Age', 'Fare'])

In [ ]:
train= median_imputer.transform(train)
test= median_imputer.transform(test)

In [ ]:
train[train.columns.drop('Survived')] = train[train.columns.drop('Survived')].fillna('Missing')
test[test.columns.drop('Survived')] = test[test.columns.drop('Survived')].fillna('Missing')

In [ ]:
test.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,title,apha_ticket,cabin_type
0,None,3,male,34.5,0,0,7.8292,Q,Mr,0,Missing
1,None,3,female,47.0,1,0,7.0000,S,Mrs,0,Missing
2,None,2,male,62.0,0,0,9.6875,Q,Mr,0,Missing
3,None,3,male,27.0,0,0,8.6625,S,Mr,0,Missing
4,None,3,female,22.0,1,1,12.2875,S,Mrs,0,Missing

In [ ]:
train['Parch'].value_counts()

Parch
0    678
1    118
2     80
5      5
3      5
4      4
6      1
Name: count, dtype: int64

In [ ]:
from feature_engine.encoding import *
from feature_engine.discretisation import *

In [ ]:
cat_var = ['Sex', 'title', 'cabin_type', 'Embarked', 'Pclass', 'Parch', 'SibSp']

num_var = ['Age', 'Fare']
y_var = 'Survived'
regression = False

In [ ]:
!pip install datasets

Collecting datasets
  Downloading datasets-2.18.0-py3-none-any.whl (510 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 510.5/510.5 KB 3.5 MB/s eta 0:00:00[36m0:00:01[36m0:00:01
Collecting xxhash
  Downloading xxhash-3.4.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 KB 17.1 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.17 in ./.azenv/lib/python3.10/site-packages (from datasets) (1.26.4)
Collecting multiprocess
  Downloading multiprocess-0.70.16-py310-none-any.whl (134 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 KB 13.5 MB/s eta 0:00:00
Requirement already satisfied: packaging in ./.azenv/lib/python3.10/site-packages (from datasets) (23.2)
Requirement already satisfied: pyyaml>=5.1 in ./.azenv/lib/python3.10/site-packages (from datasets) (6.0.1)
Collecting aiohttp
  Downloading aiohttp-3.9.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 18.3 MB/s eta 0:00:00 MB/s eta 0:00:01
Collecting dill<0.3.9,>=0.3.0
  Downloading dill-0.3.8-py3-none-any.whl (116 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 KB 11.7 MB/s eta 0:00:00
Collecting pyarrow>=12.0.0
  Downloading pyarrow-15.0.0-cp310-cp310-manylinux_2_28_x86_64.whl (38.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.3/38.3 MB 27.3 MB/s eta 0:00:00m eta 0:00:01[36m0:00:01
Collecting tqdm>=4.62.1
  Downloading tqdm-4.66.2-py3-none-any.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.3/78.3 KB 4.4 MB/s eta 0:00:00
Collecting huggingface-hub>=0.19.4
  Downloading huggingface_hub-0.21.3-py3-none-any.whl (346 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 346.2/346.2 KB 37.5 MB/s eta 0:00:00
Collecting fsspec[http]<=2024.2.0,>=2023.1.0
  Downloading fsspec-2024.2.0-py3-none-any.whl (170 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.9/170.9 KB 23.1 MB/s eta 0:00:00
Requirement already satisfied: requests>=2.19.0 in ./.azenv/lib/python3.10/site-packages (from datasets) (2.31.0)
Collecting pyarrow-hotfix
  Downloading pyarrow_hotfix-0.6-py3-none-any.whl (7.9 kB)
Collecting filelock
  Using cached filelock-3.13.1-py3-none-any.whl (11 kB)
Requirement already satisfied: pandas in ./.azenv/lib/python3.10/site-packages (from datasets) (2.2.1)
Requirement already satisfied: attrs>=17.3.0 in ./.azenv/lib/python3.10/site-packages (from aiohttp->datasets) (23.2.0)
Collecting frozenlist>=1.1.1
  Downloading frozenlist-1.4.1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (239 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 239.5/239.5 KB 30.0 MB/s eta 0:00:00
Collecting yarl<2.0,>=1.0
  Downloading yarl-1.9.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (301 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 301.6/301.6 KB 27.7 MB/s eta 0:00:00
Collecting aiosignal>=1.1.2
  Downloading aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting async-timeout<5.0,>=4.0
  Downloading async_timeout-4.0.3-py3-none-any.whl (5.7 kB)
Collecting multidict<7.0,>=4.5
  Downloading multidict-6.0.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (124 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.3/124.3 KB 17.8 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=3.7.4.3 in ./.azenv/lib/python3.10/site-packages (from huggingface-hub>=0.19.4->datasets) (4.10.0)
Requirement already satisfied: certifi>=2017.4.17 in ./.azenv/lib/python3.10/site-packages (from requests>=2.19.0->datasets) (2024.2.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.azenv/lib/python3.10/site-packages (from requests>=2.19.0->datasets) (2.2.1)
Requirement already satisfied: idna<4,>=2.5 in ./.azenv/lib/python3.10/site-packages (from requests>=2.19.0->datasets) (3.6)
Requirement already satisfied: charset-normalizer<4,>=2 in ./.azenv/lib/python3.10/site-packages (from requests>=2.19.0->datasets) (3.3.2)
Requirement already satisfied: tzdata>=2022.7 in ./.azenv/lib/python3.10/site-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: pytz>=2020.1 in ./.azenv/lib/python3.10/site-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.azenv/lib/python3.10/site-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: six>=1.5 in ./.azenv/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.16.0)
Installing collected packages: xxhash, tqdm, pyarrow-hotfix, pyarrow, multidict, fsspec, frozenlist, filelock, dill, async-timeout, yarl, multiprocess, huggingface-hub, aiosignal, aiohttp, datasets
Successfully installed aiohttp-3.9.3 aiosignal-1.3.1 async-timeout-4.0.3 datasets-2.18.0 dill-0.3.8 filelock-3.13.1 frozenlist-1.4.1 fsspec-2024.2.0 huggingface-hub-0.21.3 multidict-6.0.5 multiprocess-0.70.16 pyarrow-15.0.0 pyarrow-hotfix-0.6 tqdm-4.66.2 xxhash-3.4.1 yarl-1.9.4

## discretitzation

In [ ]:
import os
import glob

In [ ]:

def feat_discretiser(train, test, num_var, cat_var, y = None, method = ['efd', 'ewd', 'dtd', 'gwd'], bins = 10):
    
    if not os.path.exists('.feataz'):
        os.mkdir('.feataz')
        
    files = glob.glob('.feataz/*')
    for f in files:
        os.remove(f)


    if 'dtd' in method and y == None:
        raise Exception("If you are using a dtd (DecisionTreeDiscretiser) please provide the valid target!!")
    
    efd = EqualFrequencyDiscretiser(q = bins, variables=num_var)
    ewd = EqualWidthDiscretiser(bins = bins, variables=num_var)
    dtd = DecisionTreeDiscretiser(cv = 3, 
                                    scoring='neg_mean_squared_error',
                                    variables = num_var,
                                    regression = False)
    gwd = GeometricWidthDiscretiser(bins = bins,
                                      variables = num_var)
    

    method_all = {'efd': efd,
                 'ewd': ewd,
                 'dtd' : dtd,
                  'gwd': gwd
                 }
    
    for i in method:
        print(i)
        dsc = method_all.get(i)
        if i == 'dtd':
            dsc.fit(train[num_var], train[y])
        else:
            dsc.fit(train[num_var])
        train_dsc = disc.transform(train[num_var])
        test_dsc = disc.transform(test[num_var])
        
        if i == 'dtd':
            train_dsc = train_dsc.rank(method = 'dense')
            test_dsc = test_dsc.rank(method = 'dense')
            
        train_dsc.columns=  [f'{i}_{x}' for x in num_var]
        test_dsc.columns =  [f'{i}_{x}' for x in num_var]


        
        for j in train_dsc.columns:
            train_dsc[[j]].to_parquet(f'.feataz/train_{j}.parquet')
            test_dsc[[j]].to_parquet(f'.feataz/test_{j}.parquet')
    print('Done: features saved in ./.feat directory!')
    return None

In [ ]:
dsc = discretiser(train, test, num_var, cat_var, y = 'Survived')

efd
ewd
dtd
gwd
Done: features saved in ./.feat directory!

In [ ]:
def feat_encoding(train, test, num_var, cat_var, y = None, method = ['ohe', 'cfe', 'me', 'rle', 'woe', 'dte'], bins = 10):
    
    if 'dte' in method and y == None:
        raise Exception("If you are using a dtd (DecisionTreeDiscretiser) please provide the valid target!!")
    
    ohe = OneHotEncoder(
        top_categories=3,
        variables= cat_var
    )
    
    cfe = CountFrequencyEncoder(
        encoding_method = 'frequency',
        variables = cat_var,
        ignore_format = True
    )
    
    
    me = MeanEncoder(
        variables = cat_var,
        ignore_format = True
    )
    
    rle = RareLabelEncoder(
        tol=0.1,
        n_categories=2,
        variables=cat_var,
        ignore_format=True,
    )
    
    woe = WoEEncoder(
        variables= cat_var,
        ignore_format=True,
    )
    
    dte = DecisionTreeEncoder(
        variables=cat_var,
        regression=False,
        scoring='roc_auc',
        cv=3,
        random_state=0,
        ignore_format=True)

    method_all = {'ohe': ohe,
                 'cfe': cfe,
                 'me' : me,
                  'rle': rle,
                  'woe': woe,
                  'dte' : dte
                 }
    trx = pd.DataFrame([])
    for i in method:
        print(i)
        dsc = method_all.get(i)
        if i == 'dtd':
            dsc.fit(train[num_var], train[y])
        else:
            dsc.fit(train[num_var])
        train_dsc = disc.transform(train[num_var])
        test_dsc = disc.transform(test[num_var])
        
        if i == 'dtd':
            train_dsc = train_dsc.rank(method = 'dense')
            test_dsc = test_dsc.rank(method = 'dense')
            
        train_dsc.columns=  [f'{i}_{x}' for x in num_var]
        test_dsc.columns =  [f'{i}_{x}' for x in num_var]

        trx = pd.concat([trx, train_dsc], axis = 1 )
    #     for j in train_dsc.columns:
    #         train_dsc[[j]].to_parquet(f'.feataz/train_{j}.parquet')
    #         test_dsc[[j]].to_parquet(f'.feataz/test_{j}.parquet')
    # print('Done: features saved in ./.feat directory!')
    return trx

In [98]:
from datasets import load_dataset

trx = load_dataset('parquet', data_files = './train_dsc.parquet')

Generating train split: 0 examples [00:00, ? examples/s]

In [100]:
dsc

,efd_Age,efd_Fare,ewd_Age,ewd_Fare,dtd_Age,dtd_Fare,gwd_Age,gwd_Fare
0,2,0,2,0,0.366114,0.218855,7,3
1,5,8,4,1,0.366114,0.441758,8,6
2,3,2,3,0,0.366114,0.218855,7,3
3,5,8,4,1,0.366114,0.441758,8,6
4,5,2,4,0,0.366114,0.218855,8,3
...,...,...,...,...,...,...,...,...
886,3,4,3,0,0.366114,0.441758,7,4
887,1,7,2,0,0.366114,0.441758,6,5
888,3,6,3,0,0.366114,0.441758,7,5
889,3,7,3,0,0.366114,0.441758,7,5
890,4,1,3,0,0.366114,0.218855,7,3

In [15]:

disc = EqualFrequencyDiscretiser(q = 10, variables=num_var)

disc.fit(train[num_var])

train_efd = disc.transform(train[num_var])
test_efd = disc.transform(test[num_var])

In [16]:
disc = EqualWidthDiscretiser(bins = 10, variables=num_var)

disc.fit(train[num_var])

train_ewd = disc.transform(train[num_var])
test_ewd = disc.transform(test[num_var])

In [17]:
test_ewd

     Age  Fare
0      4     0
1      5     0
2      7     0
3      3     0
4      2     0
..   ...   ...
413    3     0
414    4     2
415    4     0
416    3     0
417    3     0

[418 rows x 2 columns]

In [18]:
disc = DecisionTreeDiscretiser(cv = 3, 
                            scoring='neg_mean_squared_error',
                            variables = num_var,
                            regression = False)

disc.fit(train[num_var], train[y_var])

train_dtd = disc.transform(train[num_var])
test_dtd = disc.transform(test[num_var])

In [19]:
disc = GeometricWidthDiscretiser(bins = 10,
                                  variables = num_var)

disc.fit(train[num_var])

train_gwd = disc.transform(train[num_var])

test_gwd = disc.transform(test[num_var])

In [ ]:
# disc = DecisionTreeDiscretiser(cv = 3, 
#                             scoring='neg_mean_squared_error',
#                             variables = num_var,
#                             regression = False)

# disc.fit(train[num_var], train[y_var])

# train_dtd = disc.transform(train[num_var])
# test_dtd = disc.transform(test[num_var])

In [ ]:
ohe = OneHotEncoder(
    top_categories=3,
    variables= cat_var
)

cfe = CountFrequencyEncoder(
    encoding_method = 'frequency',
    variables = cat_var,
    ignore_format = True
)


me = MeanEncoder(
    variables = cat_var,
    ignore_format = True
)

rle = RareLabelEncoder(
    tol=0.1,
    n_categories=2,
    variables=cat_var,
    ignore_format=True,
)

woe = WoEEncoder(
    variables= cat_var,
    ignore_format=True,
)

dte = DecisionTreeEncoder(
    variables=cat_var,
    regression=False,
    scoring='roc_auc',
    cv=3,
    random_state=0,
    ignore_format=True)

## Encoding

In [20]:
encoder = OneHotEncoder(
    top_categories=3,
    variables= ['Sex', 'title', 'cabin_type', 'Embarked', 'Pclass']
)
# fit the encoder
encoder.fit(train[['Sex', 'title', 'cabin_type', 'Embarked', 'Pclass']])

OneHotEncoder(top_categories=3,
              variables=['Sex', 'title', 'cabin_type', 'Embarked', 'Pclass'])

In [21]:
one_hot_train= encoder.transform(train[['Sex', 'title', 'cabin_type', 'Embarked', 'Pclass']])
one_hot_test= encoder.transform(test[['Sex', 'title', 'cabin_type', 'Embarked', 'Pclass']])

In [22]:
enc = CountFrequencyEncoder(
    encoding_method = 'frequency',
    variables = cat_var,
    ignore_format = True
)

In [23]:
enc.fit(train[cat_var])

CountFrequencyEncoder(encoding_method='frequency', ignore_format=True,
                      variables=['Sex', 'title', 'cabin_type', 'Embarked',
                                 'Pclass', 'Parch', 'SibSp'])

In [24]:
cnt_freq_train= enc.transform(train[cat_var])
cnt_freq_test= enc.transform(test[cat_var])

/home/zaenal/feataz/.azenv/lib/python3.10/site-packages/feature_engine/encoding/base_encoder.py:255: UserWarning: During the encoding, NaN values were introduced in the feature(s) title, Parch.
  warnings.warn(

In [26]:
enc = MeanEncoder(
    variables = cat_var,
    ignore_format = True
)

In [29]:
enc.fit(train[cat_var], train['Survived'])
mean_enc_train= enc.transform(train[cat_var])
mean_enc_test= enc.transform(test[cat_var])

/home/zaenal/feataz/.azenv/lib/python3.10/site-packages/feature_engine/encoding/base_encoder.py:255: UserWarning: During the encoding, NaN values were introduced in the feature(s) title, Parch.
  warnings.warn(

In [37]:
# set up a weight of evidence encoder
# set up a rare label encoder
rare_encoder = RareLabelEncoder(
    tol=0.1,
    n_categories=2,
    variables=cat_var,
    ignore_format=True,
)

# fit and transform data
train_t = rare_encoder.fit_transform(train)
test_t = rare_encoder.transform(test)


woe_encoder = WoEEncoder(
    variables= cat_var,
    ignore_format=True,
)

# fit the encoder
woe_encoder.fit(train_t[cat_var], train_t['Survived'])
woe_train= woe_encoder.transform(train_t[cat_var])
woe_test= woe_encoder.transform(test_t[cat_var])

/home/zaenal/feataz/.azenv/lib/python3.10/site-packages/feature_engine/encoding/rare_label.py:216: UserWarning: The number of unique categories for variable Sex is less than that indicated in n_categories. Thus, all categories will be considered frequent
  warnings.warn(
/home/zaenal/feataz/.azenv/lib/python3.10/site-packages/feature_engine/encoding/rare_label.py:255: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Rare' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  X.loc[
/home/zaenal/feataz/.azenv/lib/python3.10/site-packages/feature_engine/encoding/rare_label.py:255: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Rare' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  X.loc[
/home/zaenal/feataz/.azenv/lib/python3.10/site-packages/feature_engine/encoding/rare_label.py:255: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Rare' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  X.loc[
/home/zaenal/feataz/.azenv/lib/python3.10/site-packages/feature_engine/encoding/rare_label.py:255: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Rare' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  X.loc[

In [48]:
encoder = DecisionTreeEncoder(
    variables=cat_var,
    regression=False,
    scoring='roc_auc',
    cv=3,
    random_state=0,
    ignore_format=True)

encoder.fit(train_t[cat_var], train_t['Survived'])

DecisionTreeEncoder(ignore_format=True, random_state=0, regression=False,
                    scoring='roc_auc',
                    variables=['Sex', 'title', 'cabin_type', 'Embarked',
                               'Pclass', 'Parch', 'SibSp'])

In [49]:
dec_train= encoder.transform(train_t[cat_var])
dec_test= encoder.transform(test_t[cat_var])

In [154]:
train_dtd.rank(method = 'dense')['Age'].value_counts()
# ['average', 'min', 'max', 'first', 'dense']

Age
1.0    844
2.0     47
Name: count, dtype: int64

## Feature Creation

In [ ]:
from feature_engine.creation import MathFeatures

transformer = MathFeatures(
    variables=["Age", "Marks"],
    func = ["sum", "prod", "min", "max", "std"],
)

df_t = transformer.fit_transform(df)

print(df_t)

In [45]:
import warnings
class FeatInteraction():
    def __init__(self, group, 
                 value = None
                 , metric = ['min', 'max', 'mean', 'median', 'std'],
                 date_index = None,
                 date_feature = ['15d', '45d' , '1m', '2m', '3m', '6m', '12m', '2y']) -> None:
        if not isinstance(group, list):
            if isinstance(group, str):
                group = [group]
            else:
                group = list(group)
        
        super().__init__()

        self.group = group
        self.value = value
        self.metric = metric
        self.date_index = date_index
        self.date_feature = date_feature
    
    def fit(self, df):
        if not self.value:
            warnings.warn('value are set to None, the metric paramaters will be ignore. The metric will be set to count')

        #df = super().fit(df)
        if self.date_index:
            warnings.warn('The feature creation based using date are not available yet. please staytune for the update')
            self.date_index = None



        if not self.date_index :
            if not self.value:
                grp = df.groupby(self.group).size().reset_index()
                grp.columns = grp + ['count_' + '_'.join(grp)]
                
            else:
                grp = df.groupby(self.group)[self.value].agg(self.metric).reset_index()
                cols = grp.columns[grp.columns.isin(self.group) == False]

                cols = [f'{self.value}_{x}_of_' + '_'.join(self.group) for x in cols]
                grp.columns = self.group + cols
        self.grp = grp
        return self
    

    def transform(self, df):

        res = df.merge(self.grp, how = 'left', on = self.group)

        return res

In [46]:
feat_int = FeatInteraction(['Sex', 'Pclass'], 'Age')

In [47]:
feat_int.fit(train)

In [48]:
feat_int.transform(train)

,Survived,Pclass,Sex,Age,SibSp,...,Age_min_of_Sex_Pclass,Age_max_of_Sex_Pclass,Age_mean_of_Sex_Pclass,Age_median_of_Sex_Pclass,Age_std_of_Sex_Pclass
0,0,3,male,22.0,1,...,0.42,74.0,26.911873,28.0,10.398394
1,1,1,female,38.0,1,...,2.00,63.0,33.978723,32.5,13.083667
2,1,3,female,26.0,0,...,0.75,63.0,23.572917,28.0,11.071718
3,1,1,female,35.0,1,...,2.00,63.0,33.978723,32.5,13.083667
4,0,3,male,35.0,0,...,0.42,74.0,26.911873,28.0,10.398394
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,...,0.67,70.0,30.512315,29.0,14.178495
887,1,1,female,19.0,0,...,2.00,63.0,33.978723,32.5,13.083667
888,0,3,female,28.0,1,...,0.75,63.0,23.572917,28.0,11.071718
889,1,1,male,26.0,0,...,0.92,80.0,38.995246,36.0,14.655079
890,0,3,male,32.0,0,...,0.42,74.0,26.911873,28.0,10.398394

In [49]:
feat_int.transform(test)

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,title,apha_ticket,cabin_type,Age_min_of_Sex_Pclass,Age_max_of_Sex_Pclass,Age_mean_of_Sex_Pclass,Age_median_of_Sex_Pclass,Age_std_of_Sex_Pclass
0,None,3,male,34.5,0,0,7.8292,Q,Mr,0,Missing,0.42,74.0,26.911873,28.0,10.398394
1,None,3,female,47.0,1,0,7.0000,S,Mrs,0,Missing,0.75,63.0,23.572917,28.0,11.071718
2,None,2,male,62.0,0,0,9.6875,Q,Mr,0,Missing,0.67,70.0,30.512315,29.0,14.178495
3,None,3,male,27.0,0,0,8.6625,S,Mr,0,Missing,0.42,74.0,26.911873,28.0,10.398394
4,None,3,female,22.0,1,1,12.2875,S,Mrs,0,Missing,0.75,63.0,23.572917,28.0,11.071718
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,None,3,male,28.0,0,0,8.0500,S,Mr,1,Missing,0.42,74.0,26.911873,28.0,10.398394
414,None,1,female,39.0,0,0,108.9000,C,Dona,1,C,2.00,63.0,33.978723,32.5,13.083667
415,None,3,male,38.5,0,0,7.2500,S,Mr,1,Missing,0.42,74.0,26.911873,28.0,10.398394
416,None,3,male,28.0,0,0,8.0500,S,Mr,0,Missing,0.42,74.0,26.911873,28.0,10.398394
417,None,3,male,28.0,1,1,22.3583,C,Master,0,Missing,0.42,74.0,26.911873,28.0,10.398394